
;----------------------------------------------
COINITBASE_MULTITHREADED            uniq  0x0;OLE calls objects on any thread.
COINIT_APARTMENTTHREADED            uniq  0x2;Apartment model
COINIT_MULTITHREADED                uniq  COINITBASE_MULTITHREADED
COINIT_DISABLE_OLE1DDE              uniq  0x4;Don't use DDE for Ole1 support.
COINIT_SPEED_OVER_MEMORY            uniq  0x8;Trade memory for speed.