
; Win32 programming headers (WideChar)

        LpType fix dd
include 'My\Const.inc'



include 'My\Macro\Other.inc'
include 'My\Macro\Debug.inc'
include 'My\Macro\Struct.inc'
include 'My\Macro\Import32.inc'
include 'My\Macro\EXPORT.INC'
include 'My\Macro\Proc32.inc'
include 'My\Macro\Resource.inc'

include 'My\Equates\Objbase.inc'
include 'My\Equates\CommDlg.inc'
include 'My\Equates\ShellApi.inc'
include 'My\Equates\WinGdi.inc'
include 'My\Equates\CommCtrl.inc'
include 'My\Equates\HandleApi.inc'
include 'My\Equates\LibloaderApi.inc'
include 'My\Equates\FileApi.inc'
include 'My\Equates\ShlObj_core.inc'
include 'My\Equates\KnownFolders.inc'
include 'My\Equates\Verrsrc.inc'
include 'My\Equates\WinNt.inc'
include 'My\Equates\WinReg.inc'
include 'My\Equates\WinUser.inc'
include 'My\Equates\WinBase.inc'
include 'My\Equates\WinError.inc'
include 'My\Equates\Struct.inc'

