
; Win64 programming headers (WideChar)

        LpType fix dq
include 'My\Const.inc'


include 'Fasm\MACRO\RESOURCE.INC'
include 'Fasm\ENCODING\WIN1251.INC'

include 'My\Macro\Debug.inc'
include 'My\Macro\Struct.inc'
;include 'My\Macro\Import32.inc'
;include 'My\Macro\Proc32.inc'

include 'My\Equates\Verrsrc.inc'
include 'My\Equates\WinNt.inc'
include 'My\Equates\WinReg.inc'
include 'My\Equates\WinUser.inc'